---
abstract: 'get VT updates in increments'
author:
  - 'Jason May <jason.a.may@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-VT102-Incremental
requires:
  Moose: 0.51
  Term::VT102: 0
version: 0.01
